### PR TITLE
Fixing context value. NGSI parameter is called value in the…

### PR DESCRIPTION
**Pull request by geonexus**
### REVIEWERS
@flopezag @jframos 

### DESCRIPTION
Fixing context value. NGSI parameter is called value in the latest release of NGSI.

### CODE REVIEW

**Comment by flopezag** [comment]
You do not need to change some unit tests or acceptance tests?

**Comment by geonexus** [comment]
No I do not.
Data contains the value needed for all unit tests.

**Comment by flopezag** [comment]
LGTM

**Comment by jframos** [comment]
LGTM

**Pull request merged**
