### PR TITLE
Fixing cobertura 

### PR DESCRIPTION
**Pull request by geonexus**
### REVIEWERS
@flopezag 

### DESCRIPTION
fixing some dependencies, adding sudo to some commands and giving permissions to some folders

### CODE REVIEW

**Comment by flopezag** [comment]
one question taking into account those changes, it was resolve the problem of the coverage, I mean, the different values that I have compared with the data that actually show sonar...

**Comment by geonexus** [comment]
There are some problems with different values, it takes 76% coverage executing tose unit tests instead of 91% executing the tests in local

**Comment by flopezag** [comment]
What is the difference, because in the IDE give also de same values. Maybe you are taking different number of LOC?

**Comment by geonexus** [comment]
The problem seems to be when you start nosetests in Linux instead of OS X.

**Comment by flopezag** [comment]
LGTM

**Pull request merged**
