### PR TITLE
fixing windowsize value before adding it to the reds queue.

### PR DESCRIPTION
**Pull request by geonexus**
### REVIEWERS
@jframos 

### DESCRIPTION
- fixing windowsize value before adding it to the redis queue.

### CODE REVIEW

**Comment by flopezag** [comment]
one question, the issue #43 does not resolve this issue?

**Comment by geonexus** [comment]
I see that it is nasted

**Comment by jframos** [comment]
They have been detected by different test cases. That is why there are two tickets.
LGTM

**Comment by jframos** [comment]
But it is true, this fix is in the other PR...

**Pull request closed without merging**
