### PR TITLE
fixing unittests

### PR DESCRIPTION
**Pull request by geonexus**
### REVIEWERS
@flopezag @jframos 

### DESCRIPTION
- fixing unit test errors
- fixed log message when a windowsize is received
- added xunit report to build file.

### CODE REVIEW

**Comment by jframos** [comment]
LGTM

Why isn't travis running unit tests?

**Comment by geonexus** [comment]
The command "sudo ./build.sh travis_build" exited with 0.
--> build.sh should exit with 1 when something is wrong. It is not happening for some reasons :S

**Comment by flopezag** [comment]
LGTM

**Comment by jframos** [comment]
To be fixed in *CLAUDIA-5609*.
LGTM

**Pull request merged**
